#cloud-config
preserve_hostname: true
manage_etc_hosts: false

bootcmd:
 - "echo ${HOSTNAME}-$INSTANCE_ID.${REGION_DNS} > /etc/hostname; hostname -F /etc/hostname"
 - "sed -i -e '/^127.0.0.1/d' /etc/hosts; echo 127.0.0.1 ${HOSTNAME}-$INSTANCE_ID.${REGION_DNS} ${HOSTNAME}-$INSTANCE_ID localhost >> /etc/hosts"
 - "echo ${MASTER_IP} spark-master >> /etc/hosts"

# set the locale
locale: en_GB.UTF-8

# timezone: set the timezone for this instance (ALWAYS use UTC!)
timezone: UTC

# Don't print the new ssh keys on the console
no_ssh_fingerprints: true
# Don't override our apt repository list on first boot
apt_preserve_sources_list: true

writes_files:
 - path: /etc/ansible/hosts
   owner: ubuntu:ubuntu
   permissions: '0444'
   content: |
     localhost ansible_connection=local

runcmd:
 - "while [ ! -e '/dev/xvdd' ]; do echo 'waiting for device: xvdd'; sleep 1; done"
 - yes | sudo apt-get update -y -qq
 - sudo apt-get install -y xfsprogs
 - sudo mkfs -t xfs /dev/xvdd
 - sudo mkdir /vol
 - sudo mount /dev/xvdd /vol
 - echo "/dev/xvdd       /vol    xfs    defaults,noatime       0       0" >> /etc/fstab
 - /usr/local/bin/ansible-pull -o -C auto-provision -d /opt/ansible -U https://github.com/datavisortianli/terraform-demo.git --e "env=${ENV} role=${ROLE}">> /var/log/ansible-pull.log 2>&1